apiVersion: v1
kind: ConfigMap
metadata:
  name: wealthcare-config-map
  namespace: wealthcare-ns
  labels:
    app: wealthcare-application
    subname: configmap
type: Opaque
data:
  ##### User and FinancialPlan services
  # apiUrlUser: http://wealthcare-user-wealthcare-ns.gsidevint-4c84f19c22000.us-south.containers.appdomain.cloud/
  # apiUrlFinancialplan: http://wealthcare-financialplan-wealthcare-ns.gsidevint-4c77-0000.us-south.containers.appdomain.cloud/
  apiUrlUser: http://wealthcare-user-wealthcare-ns.gsidevint-4c84f19c22c6eb1784ba9d2966faea77-0000.us-south.containers.appdomain.cloud/
  apiUrlFinancialplan: http://wealthcare-financialplan-wealthcare-ns.gsidevint-4c84f19c22c6eb1784ba9d2966faea77-0000.us-south.containers.appdomain.cloud/
  ##### MQ
  configMapMqConnName: 111.222.333.444(1414)
  configMapMqQueueManager: qmgr
  configMapMqChannel: DEV.APP.SVRCONN
  configMapMqQueueNameFinancialPlan: DEV.QUEUE.1
  configMapMqQueueNameCustomer: DEV.QUEUE.2
  configMapMqQueueNameWealthManager: DEV.QUEUE.3
  configMapMqDeadQueueName: DEV.DEAD.LETTER.QUEUE
  ##### DB-H2
  databaseUrl: jdbc:h2:mem:/wcare
  databaseUsername: admin
  databasePassword: admin
  databaseDriverClass: org.h2.Driver
  databasePlatform: org.hibernate.dialect.H2Dialect
  ##### DB-MySQL
  # databaseUrl: jdbc:mysql://222.222.333.333:3306/wcare
  # databaseUsername: usr
  # databasePassword: pwddd
  # databaseDriverClass: com.mysql.jdbc.Driver
  # databasePlatform: org.hibernate.dialect.MySQL5Dialect
  ##### DB-DB2
  # databaseUrl: jdbc:db2://111.222.33.444:31463/wcare
  # databaseUsername: usr
  # databasePassword: pwddd
  # databaseDriverClass: com.ibm.db2.jcc.DB2Driver
  # databasePlatform: org.hibernate.dialect.DB2Dialect
  ##### Notification
  configMapAppNotificationFrom: test
  configMapAppNotificationCC: test
  configMapAppNotificationOpenWhiskUser: testconfigmap.test1.key
  configMapAppNotificationOpenWhiskPassword: test
  configMapAppNotificationOpenWhiskUrl: test@teset11.com
  ##### Watson FinancialPlan
  watsonOptionEnabled: "false"
  watsonUrlFinancialPlan: https://test@test11.com